# Generated by Django 5.0.6 on 2026-06-20 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('update_times', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_cz', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('rate_buy', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('rate_sell', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('rate_mid', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('valid_from', models.DateField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='rates.bank')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='rates.currency')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['currency', '-fetched_at'], name='rates_excha_currenc_b058df_idx'), models.Index(fields=['bank', 'currency', '-fetched_at'], name='rates_excha_bank_id_473213_idx')],
            },
        ),
    ]
